import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>This is header</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
